---
- hosts: "{{TARGET_HOST}}"
  name: Disable swap space
  remote_user: <SUDO USER ACCOUNT>
  vars_files:
  - /data/ansible/playbooks/vars/main/aws_vars.yml
  vars:
   ansible_ssh_private_key_file: "{{key}}"
  become: yes
  gather_facts: yes
  roles:
  - {role: ../roles/disable_swap}
